### ISSUE TITLE
TypeError: Cannot read property 'map' of null

### ISSUE THREAD

**Issue by Blackbaud-KrisMahon** [blackbaud/skyux-builder-resource-linter#8]
I ran into this issue running `skyux lint-resources` using version `1.0.0-rc.0`.  It doesn't seem to affect anything.  It still seems to find all my resource string issues (that I know of).

```
SKY UX is processing the 'lint-resources' command.
Problem with ts reference app-test-module-metadata.ts TypeError: Cannot read property 'map' of null
    at files.reduce (C:\Code\Products\_git\skyux-spa-event-mgmt\node_modules\@blackbaud\skyux-builder-resource-linter\src\lint-resources.js:112:87)
    at Array.reduce (<anonymous>)
    at getTSReferences (C:\Code\Products\_git\skyux-spa-event-mgmt\node_modules\@blackbaud\skyux-builder-resource-linter\src\lint-resources.js:103:30)
    at lintResources (C:\Code\Products\_git\skyux-spa-event-mgmt\node_modules\@blackbaud\skyux-builder-resource-linter\src\lint-resources.js:20:20)
    at Object.runCommand (C:\Code\Products\_git\skyux-spa-event-mgmt\node_modules\@blackbaud\skyux-builder-resource-linter\index.js:22:40)
    at globs.forEach.pkg (C:\nvm\v10.16.2\node_modules\@skyux-sdk\cli\index.js:68:20)
    at Array.forEach (<anonymous>)
    at getModulesAnswered (C:\nvm\v10.16.2\node_modules\@skyux-sdk\cli\index.js:47:9)
    at invokeCommand (C:\nvm\v10.16.2\node_modules\@skyux-sdk\cli\index.js:119:27)
    at processArgv (C:\nvm\v10.16.2\node_modules\@skyux-sdk\cli\index.js:183:3)
```

**Comment by Blackbaud-MitchellThomas** [comment]
This does actually harm the validity of what the linter returns due to poor error handling. I'm working on a fix for it.

**Comment by Blackbaud-MitchellThomas** [comment]
@Blackbaud-KrisMahon, RC2 fixes this issue. You can give it a try.

**Comment by Blackbaud-KrisMahon** [comment]
@Blackbaud-MitchellThomas RC2 does seem to fix this error for me.

**Comment by Blackbaud-MitchellThomas** [comment]
Ok, great! I'll close this issue then.
